# Generated by Django 4.2.23 on 2026-02-23 16:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_add_comentario_proyecto'),
    ]

    operations = [
        migrations.CreateModel(
            name='Eje',
            fields=[
                ('id_eje', models.IntegerField(primary_key=True, serialize=False)),
                ('nombre_eje', models.CharField(max_length=300)),
            ],
            options={
                'verbose_name': 'Eje',
                'verbose_name_plural': 'Ejes',
                'ordering': ['id_eje'],
            },
        ),
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('id_plan', models.IntegerField(primary_key=True, serialize=False)),
                ('nombre_plan', models.CharField(max_length=300)),
                ('proposito_politica_publica', models.TextField(blank=True)),
                ('vision_estrategica', models.TextField(blank=True)),
                ('eje', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='planes', to='projects.eje')),
            ],
            options={
                'verbose_name': 'Plan',
                'verbose_name_plural': 'Planes',
                'ordering': ['id_plan'],
            },
        ),
        migrations.CreateModel(
            name='Programa',
            fields=[
                ('id_programa', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('nombre_programa', models.CharField(max_length=500)),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='programas', to='projects.plan')),
            ],
            options={
                'verbose_name': 'Programa',
                'verbose_name_plural': 'Programas',
                'ordering': ['id_programa'],
            },
        ),
        migrations.CreateModel(
            name='ObjetivoEstrategico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.TextField()),
                ('programa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='objetivos_estrategicos', to='projects.programa')),
            ],
            options={
                'verbose_name': 'Objetivo Estratégico',
                'verbose_name_plural': 'Objetivos Estratégicos',
                'ordering': ['id'],
            },
        ),
        migrations.AddField(
            model_name='proyecto',
            name='programa',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='proyectos', to='projects.programa'),
        ),
    ]
