# Generated by Django 4.2.23

from django.db import migrations, models
import django.db.models.deletion


def migrar_datos(apps, schema_editor):
    """Migra datos: usuario_responsable=creado_por, area desde ProyectoArea si existe."""
    Proyecto = apps.get_model('projects', 'Proyecto')
    ProyectoArea = apps.get_model('projects', 'ProyectoArea')
    for p in Proyecto.objects.all():
        if not p.usuario_responsable_id and p.creado_por_id:
            p.usuario_responsable_id = p.creado_por_id
        if not p.area_id:
            pa = ProyectoArea.objects.filter(proyecto=p).first()
            if pa:
                p.area_id = pa.area_id
        p.save()


class Migration(migrations.Migration):

    dependencies = [
        ('areas', '0002_area_responsable'),
        ('users', '0001_initial'),
        ('projects', '0005_agregar_secretaria'),
    ]

    operations = [
        migrations.AddField(
            model_name='proyecto',
            name='usuario_responsable',
            field=models.ForeignKey(
                blank=True, null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name='proyectos_a_cargo',
                to='users.usuario'
            ),
        ),
        migrations.AddField(
            model_name='proyecto',
            name='area',
            field=models.ForeignKey(
                blank=True, null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name='proyectos',
                to='areas.area'
            ),
        ),
        migrations.CreateModel(
            name='ProyectoEquipo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('proyecto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='equipo', to='projects.proyecto')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='proyectos_equipo', to='users.usuario')),
            ],
            options={
                'verbose_name': 'Miembro del equipo',
                'verbose_name_plural': 'Equipo del proyecto',
                'unique_together': {('proyecto', 'usuario')},
            },
        ),
        migrations.RunPython(migrar_datos, migrations.RunPython.noop),
    ]
