# Generated by Django 4.2.23 on 2026-03-03 17:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_hash_passwords'),
        ('projects', '0006_proyecto_responsable_area_equipo'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdjuntoProyecto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('archivo', models.FileField(upload_to='adjuntos/proyectos/%Y/%m/')),
                ('nombre_original', models.CharField(max_length=255)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('proyecto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='adjuntos', to='projects.proyecto')),
                ('subido_por', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='users.usuario')),
            ],
            options={
                'ordering': ['-fecha'],
            },
        ),
    ]
