# Generated by Django 4.2.23 on 2026-03-03 18:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_hash_passwords'),
        ('projects', '0007_adjuntoproyecto'),
    ]

    operations = [
        migrations.AddField(
            model_name='comentarioproyecto',
            name='editado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='comentarios_proyecto_editados', to='users.usuario'),
        ),
        migrations.AddField(
            model_name='comentarioproyecto',
            name='fecha_edicion',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='ComentarioAuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('proyecto', 'Proyecto'), ('tarea', 'Tarea')], max_length=20)),
                ('comentario_id', models.IntegerField()),
                ('accion', models.CharField(choices=[('editar', 'Editar'), ('eliminar', 'Eliminar')], max_length=20)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('texto_anterior', models.TextField(blank=True)),
                ('texto_nuevo', models.TextField(blank=True)),
                ('proyecto_id', models.IntegerField(blank=True, null=True)),
                ('tarea_id', models.IntegerField(blank=True, null=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='users.usuario')),
            ],
            options={
                'ordering': ['-fecha'],
            },
        ),
    ]
