# Generated by Django 4.2.23 on 2026-03-03 19:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_hash_passwords'),
        ('projects', '0008_comentarioproyecto_editado_por_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdjuntoAuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('proyecto', 'Proyecto'), ('tarea', 'Tarea')], max_length=20)),
                ('adjunto_id', models.IntegerField()),
                ('accion', models.CharField(choices=[('editar', 'Editar'), ('eliminar', 'Eliminar')], max_length=20)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('nombre_archivo', models.CharField(blank=True, max_length=255)),
                ('nombre_anterior', models.CharField(blank=True, max_length=255)),
                ('nombre_nuevo', models.CharField(blank=True, max_length=255)),
                ('proyecto_id', models.IntegerField(blank=True, null=True)),
                ('tarea_id', models.IntegerField(blank=True, null=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='users.usuario')),
            ],
            options={
                'ordering': ['-fecha'],
            },
        ),
    ]
