# Generated by Django 4.2.23 on 2026-03-16 13:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0012_remove_proyecto_projects_proy_estado_idx'),
    ]

    operations = [
        migrations.AddField(
            model_name='proyecto',
            name='fuente_financiamiento',
            field=models.CharField(choices=[('Provincial', 'Provincial'), ('Nacional', 'Nacional'), ('CFI', 'CFI'), ('Otros', 'Otros'), ('Sin Erogacion', 'Sin Erogacion')], default='Provincial', max_length=20),
        ),
        migrations.AddField(
            model_name='proyecto',
            name='presupuesto_total',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=14),
        ),
        migrations.CreateModel(
            name='ProyectoPresupuestoItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categoria_gasto', models.CharField(choices=[('Equipamiento', 'Equipamiento'), ('Gastos operativos y logisticos', 'Gastos operativos y logisticos'), ('Dotacion', 'Dotacion')], max_length=30)),
                ('monto', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('detalle', models.CharField(blank=True, max_length=255)),
                ('numero_expediente', models.CharField(blank=True, max_length=100)),
                ('es_viaticos', models.BooleanField(default=False)),
                ('dotacion_tipo', models.CharField(blank=True, choices=[('Personal Propio', 'Personal Propio'), ('Contratacion Externa', 'Contratacion Externa')], max_length=30)),
                ('horas_hombre', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('orden', models.PositiveIntegerField(default=0)),
                ('proyecto', models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.CASCADE, related_name='presupuesto_items', to='projects.proyecto')),
            ],
            options={
                'verbose_name': 'Item presupuestario',
                'verbose_name_plural': 'Items presupuestarios',
                'ordering': ['orden', 'id'],
                'indexes': [models.Index(fields=['proyecto', 'orden'], name='proy_pres_item_ord_idx'), models.Index(fields=['categoria_gasto'], name='proy_pres_cat_idx')],
            },
        ),
        migrations.AddConstraint(
            model_name='proyectopresupuestoitem',
            constraint=models.CheckConstraint(check=models.Q(('monto__gte', 0)), name='proy_pres_monto_gte_0'),
        ),
        migrations.AddConstraint(
            model_name='proyectopresupuestoitem',
            constraint=models.CheckConstraint(check=models.Q(('horas_hombre__isnull', True), ('horas_hombre__gte', 0), _connector='OR'), name='proy_pres_horas_gte_0'),
        ),
    ]
