# Generated by Django 4.2.23 on 2026-02-11 19:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ComentarioProyecto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texto', models.TextField()),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('proyecto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comentarios', to='projects.proyecto')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='users.usuario')),
            ],
            options={
                'ordering': ['-fecha'],
            },
        ),
    ]
