# Generated by Django 4.2.23 on 2026-02-23 16:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_planificacion_2026'),
    ]

    operations = [
        migrations.AddField(
            model_name='proyecto',
            name='objetivo_estrategico',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='proyectos', to='projects.objetivoestrategico'),
        ),
        migrations.CreateModel(
            name='Indicador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.TextField(blank=True)),
                ('unidad_medida', models.CharField(blank=True, max_length=50)),
                ('frecuencia', models.CharField(blank=True, max_length=50)),
                ('proyecto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='indicadores', to='projects.proyecto')),
            ],
            options={
                'verbose_name': 'Indicador',
                'verbose_name_plural': 'Indicadores',
            },
        ),
    ]
