# Generated by Django 4.2.23 on 2026-02-23 17:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('secretarias', '0001_inicial'),
        ('projects', '0004_indicadores_y_objetivo'),
    ]

    operations = [
        migrations.AddField(
            model_name='proyecto',
            name='secretaria',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='proyectos', to='secretarias.secretaria'),
        ),
    ]
