# Generated by Django 4.2.23 on 2026-02-23 17:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('areas', '0001_initial'),
        ('secretarias', '0001_inicial'),
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tarea',
            name='secretaria',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='tareas', to='secretarias.secretaria'),
        ),
        migrations.AlterField(
            model_name='tarea',
            name='area',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='areas.area'),
        ),
    ]
