# Generated by Django 4.2.23 on 2026-02-24 16:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0005_agregar_secretaria'),
        ('tasks', '0003_historial_porcentaje_anterior'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tarea',
            name='proyecto',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tareas', to='projects.proyecto'),
        ),
    ]
