# Generated by Django 4.2.23 on 2026-02-23 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_area_secretaria_tarea_usuario'),
    ]

    operations = [
        migrations.AddField(
            model_name='historialtarea',
            name='porcentaje_anterior',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
