# Generated by Django 4.2.23 on 2026-02-27 18:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0005_tarea_estado_index'),
    ]

    operations = [
        migrations.AddField(
            model_name='tarea',
            name='tarea_padre',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subtareas', to='tasks.tarea'),
        ),
    ]
