# Generated by Django 4.2.23 on 2026-03-03 17:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_hash_passwords'),
        ('tasks', '0006_tarea_padre_subtareas'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdjuntoTarea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('archivo', models.FileField(upload_to='adjuntos/tareas/%Y/%m/')),
                ('nombre_original', models.CharField(max_length=255)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-fecha'],
            },
        ),
        migrations.CreateModel(
            name='ComentarioTarea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texto', models.TextField()),
                ('fecha', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-fecha'],
            },
        ),
        migrations.RemoveIndex(
            model_name='tarea',
            name='tasks_tarea_estado_idx',
        ),
        migrations.RemoveIndex(
            model_name='tarea',
            name='tasks_tarea_proyecto_idx',
        ),
        migrations.AddField(
            model_name='comentariotarea',
            name='tarea',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comentarios', to='tasks.tarea'),
        ),
        migrations.AddField(
            model_name='comentariotarea',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='users.usuario'),
        ),
        migrations.AddField(
            model_name='adjuntotarea',
            name='subido_por',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='users.usuario'),
        ),
        migrations.AddField(
            model_name='adjuntotarea',
            name='tarea',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='adjuntos', to='tasks.tarea'),
        ),
    ]
