# Generated by Django 4.2.23 on 2026-03-03 18:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_hash_passwords'),
        ('tasks', '0007_adjuntotarea_comentariotarea_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='comentariotarea',
            name='editado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='comentarios_tarea_editados', to='users.usuario'),
        ),
        migrations.AddField(
            model_name='comentariotarea',
            name='fecha_edicion',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
