# Generated by Django 4.2.23 on 2026-03-06 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0008_comentariotarea_editado_por_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tarea',
            name='orden',
            field=models.PositiveIntegerField(db_index=True, default=0),
        ),
    ]
