# Generated by Django 4.2.23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
        ('areas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='area',
            name='usuario_responsable_area',
            field=models.ForeignKey(
                blank=True, null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name='area_responsable',
                to='users.usuario'
            ),
        ),
    ]
