# Generated by Django 4.2.23 on 2026-02-23 17:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('secretarias', '0001_inicial'),
        ('users', '0004_alter_usuario_apellido'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='secretaria',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='usuarios', to='secretarias.secretaria'),
        ),
    ]
