# Generated by Django 4.2.23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0005_area_secretaria_tarea_usuario'),
    ]

    operations = [
        migrations.CreateModel(
            name='SystemRestoreLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('backup_file', models.CharField(max_length=255)),
                ('executed_at', models.DateTimeField(auto_now_add=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='restore_logs', to='users.usuario')),
            ],
            options={
                'verbose_name': 'Log de Restore',
                'verbose_name_plural': 'Logs de Restore',
                'ordering': ['-executed_at'],
            },
        ),
        migrations.CreateModel(
            name='ActiveSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_activity', models.DateTimeField(auto_now=True)),
                ('session_key', models.CharField(db_index=True, max_length=64, unique=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='active_sessions', to='users.usuario')),
            ],
            options={
                'verbose_name': 'Sesión activa',
                'verbose_name_plural': 'Sesiones activas',
                'ordering': ['-last_activity'],
            },
        ),
    ]
